USE ROLE ACCOUNTADMIN;

--USE WAREHOUSE
USE WAREHOUSE HCL_TRAINING;

--create roles
CREATE OR REPLACE ROLE COLLEGE_ADMIN;
CREATE OR REPLACE ROLE FACULTY_ROLE;

--create users
CREATE OR REPLACE USER ADMIN_USER
PASSWORD = 'Admin@12345!'
DEFAULT_ROLE = COLLEGE_ADMIN
MUST_CHANGE_PASSWORD = TRUE;

CREATE OR REPLACE USER FACULTY_USER
PASSWORD = 'Faculty@12345!'
DEFAULT_ROLE = FACULTY_ROLE
MUST_CHANGE_PASSWORD = TRUE;

--assign roles to users
GRANT ROLE COLLEGE_ADMIN TO USER ADMIN_USER;
GRANT ROLE FACULTY_ROLE TO USER FACULTY_USER;


-- WAREHOUSE ACCESS
GRANT USAGE ON WAREHOUSE HCL_TRAINING TO ROLE COLLEGE_ADMIN;
GRANT USAGE ON WAREHOUSE HCL_TRAINING TO ROLE FACULTY_ROLE;


GRANT USAGE ON DATABASE COLLEGE_DB TO ROLE COLLEGE_ADMIN;
GRANT USAGE ON SCHEMA COLLEGE_DB.ACADEMICS TO ROLE COLLEGE_ADMIN;


-- PRIVILEGES FOR COLLEGE_ADMIN(FULL ACCESS)
GRANT ALL PRIVILEGES ON DATABASE COLLEGE_DB TO ROLE COLLEGE_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA COLLEGE_DB.ACADEMICS TO ROLE COLLEGE_ADMIN;



-- PRIVILEGES FOR FACULTY_ROLE(READ ONLY ACCESS)

GRANT USAGE ON DATABASE COLLEGE_DB TO ROLE FACULTY_ROLE;
GRANT USAGE ON SCHEMA COLLEGE_DB.ACADEMICS TO ROLE FACULTY_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA COLLEGE_DB.ACADEMICS TO ROLE FACULTY_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA COLLEGE_DB.ACADEMICS TO ROLE FACULTY_ROLE;

-- Role Hierarchy / Faculty Role accessible by admin
GRANT ROLE FACULTY_ROLE TO ROLE COLLEGE_ADMIN;


-- TEST AS COLLEGE_ADMIN

USE ROLE ACCOUNTADMIN;
GRANT ROLE COLLEGE_ADMIN TO ROLE ACCOUNTADMIN;

USE ROLE COLLEGE_ADMIN;
USE DATABASE COLLEGE_DB;
USE SCHEMA ACADEMICS;

CREATE OR REPLACE TABLE STUDENT (
  ID INT,
  NAME STRING,
  DEPARTMENT STRING
);

INSERT INTO STUDENT VALUES (1, 'Vaishnavi', 'IT');
SELECT * FROM STUDENT;


-- FACULTY READ-ONLY PROOF
SHOW GRANTS ON TABLE COLLEGE_DB.ACADEMICS.STUDENT;


GRANT USAGE ON WAREHOUSE HCL_TRAINING TO ROLE FACULTY_ROLE;

